services:
  - type: web
    name: ucsi-web
    env: python
    branch: main
    autoDeploy: true
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn src.wsgi:app --bind 0.0.0.0:$PORT
    healthCheckPath: /manage
    envVars:
      - key: FLASK_SECRET_KEY
        generateValue: true
      - key: TELEGRAM_TOKEN
        sync: false
      - key: WEB_APP_URL
        sync: false

  - type: worker
    name: ucsi-bot
    env: python
    branch: main
    autoDeploy: true
    buildCommand: pip install -r requirements.txt
    startCommand: python -u src/telegram_bot.py
    envVars:
      - key: TELEGRAM_TOKEN
        sync: false
      - key: WEB_APP_URL
        sync: false