app = "ucsi-web"
primary_region = "sin"

[build]
  dockerfile = "UCSI/Dockerfile"

[env]
  PORT = "8080"

[processes]
  app = "gunicorn src.wsgi:app --bind 0.0.0.0:$PORT"

[http_service]
  internal_port = 8080
  force_https = true
  min_machines_running = 1
  processes = ["app"]